"""route colors

Revision ID: e69f49158d3f
Revises: 35f2493b6264
Create Date: 2026-09-14 14:12:00.910698

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "e69f49158d3f"
down_revision: str | None = "35f2493b6264"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Add the MBTA's official line colors from routes.txt (hex without "#") so the website can show
# route badges in each line's own color. Filled by the next static GTFS load.
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("routes", sa.Column("route_color", sa.Text(), nullable=True))
    op.add_column("routes", sa.Column("route_text_color", sa.Text(), nullable=True))
    # ### end Alembic commands ###


# Remove the route color columns.
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("routes", "route_text_color")
    op.drop_column("routes", "route_color")
    # ### end Alembic commands ###
