"""static gtfs tables and ingest runs

Revision ID: 99a4398e6108
Revises:
Create Date: 2026-09-13 00:48:53.598771

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "99a4398e6108"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Create the static GTFS tables (routes, trips, stops, stop_times, calendar, calendar_dates),
# feed_versions for skipping already-loaded feeds, and ingest_runs for logging job runs.
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calendar",
        sa.Column("service_id", sa.Text(), nullable=False),
        sa.Column("monday", sa.Boolean(), nullable=False),
        sa.Column("tuesday", sa.Boolean(), nullable=False),
        sa.Column("wednesday", sa.Boolean(), nullable=False),
        sa.Column("thursday", sa.Boolean(), nullable=False),
        sa.Column("friday", sa.Boolean(), nullable=False),
        sa.Column("saturday", sa.Boolean(), nullable=False),
        sa.Column("sunday", sa.Boolean(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("service_id", name=op.f("pk_calendar")),
    )
    op.create_table(
        "calendar_dates",
        sa.Column("service_id", sa.Text(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("exception_type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("service_id", "date", name=op.f("pk_calendar_dates")),
    )
    op.create_table(
        "feed_versions",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column(
            "loaded_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feed_versions")),
        sa.UniqueConstraint("version", name=op.f("uq_feed_versions_version")),
    )
    op.create_table(
        "ingest_runs",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("job", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rows", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingest_runs")),
    )
    op.create_index(
        "ix_ingest_runs_job_started_at", "ingest_runs", ["job", "started_at"], unique=False
    )
    op.create_table(
        "routes",
        sa.Column("route_id", sa.Text(), nullable=False),
        sa.Column("agency_id", sa.Text(), nullable=True),
        sa.Column("route_short_name", sa.Text(), nullable=True),
        sa.Column("route_long_name", sa.Text(), nullable=True),
        sa.Column("route_type", sa.SmallInteger(), nullable=False),
        sa.Column("route_sort_order", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("route_id", name=op.f("pk_routes")),
    )
    op.create_table(
        "stop_times",
        sa.Column("trip_id", sa.Text(), nullable=False),
        sa.Column("stop_sequence", sa.Integer(), nullable=False),
        sa.Column("stop_id", sa.Text(), nullable=False),
        sa.Column("arrival_secs", sa.Integer(), nullable=True),
        sa.Column("departure_secs", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("trip_id", "stop_sequence", name=op.f("pk_stop_times")),
    )
    op.create_index(op.f("ix_stop_times_stop_id"), "stop_times", ["stop_id"], unique=False)
    op.create_table(
        "stops",
        sa.Column("stop_id", sa.Text(), nullable=False),
        sa.Column("stop_name", sa.Text(), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lon", sa.Float(), nullable=True),
        sa.Column("location_type", sa.SmallInteger(), nullable=True),
        sa.Column("parent_station", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("stop_id", name=op.f("pk_stops")),
    )
    op.create_table(
        "trips",
        sa.Column("trip_id", sa.Text(), nullable=False),
        sa.Column("route_id", sa.Text(), nullable=False),
        sa.Column("service_id", sa.Text(), nullable=False),
        sa.Column("direction_id", sa.SmallInteger(), nullable=True),
        sa.Column("trip_headsign", sa.Text(), nullable=True),
        sa.Column("shape_id", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["route_id"], ["routes.route_id"], name=op.f("fk_trips_route_id_routes")
        ),
        sa.PrimaryKeyConstraint("trip_id", name=op.f("pk_trips")),
    )
    op.create_index(op.f("ix_trips_route_id"), "trips", ["route_id"], unique=False)
    op.create_index(op.f("ix_trips_service_id"), "trips", ["service_id"], unique=False)
    # ### end Alembic commands ###


# Drop everything upgrade() created, in reverse dependency order (trips before routes).
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trips_service_id"), table_name="trips")
    op.drop_index(op.f("ix_trips_route_id"), table_name="trips")
    op.drop_table("trips")
    op.drop_table("stops")
    op.drop_index(op.f("ix_stop_times_stop_id"), table_name="stop_times")
    op.drop_table("stop_times")
    op.drop_table("routes")
    op.drop_index("ix_ingest_runs_job_started_at", table_name="ingest_runs")
    op.drop_table("ingest_runs")
    op.drop_table("feed_versions")
    op.drop_table("calendar_dates")
    op.drop_table("calendar")
    # ### end Alembic commands ###
