"""stop events

Revision ID: ea6b3d7aeb1d
Revises: 651b8ba045fa
Create Date: 2026-09-13 01:23:23.767056

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "ea6b3d7aeb1d"
down_revision: str | None = "651b8ba045fa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Create stop_events (estimated arrivals with delay and headway) and add vehicle_positions indexes
# used to find recently active trips and load their history.
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stop_events",
        sa.Column("trip_id", sa.Text(), nullable=False),
        sa.Column("service_date", sa.Date(), nullable=False),
        sa.Column("stop_sequence", sa.Integer(), nullable=False),
        sa.Column("route_id", sa.Text(), nullable=False),
        sa.Column("direction_id", sa.SmallInteger(), nullable=True),
        sa.Column("stop_id", sa.Text(), nullable=False),
        sa.Column("vehicle_id", sa.Text(), nullable=True),
        sa.Column("observed_arrival", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scheduled_arrival", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delay_seconds", sa.Integer(), nullable=True),
        sa.Column("headway_seconds", sa.Integer(), nullable=True),
        sa.Column("scheduled_headway_seconds", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "trip_id", "service_date", "stop_sequence", name=op.f("pk_stop_events")
        ),
    )
    op.create_index(
        "ix_stop_events_observed_arrival", "stop_events", ["observed_arrival"], unique=False
    )
    op.create_index(
        "ix_stop_events_route_direction_stop_arrival",
        "stop_events",
        ["route_id", "direction_id", "stop_id", "observed_arrival"],
        unique=False,
    )
    op.create_index(
        "ix_vehicle_positions_feed_timestamp", "vehicle_positions", ["feed_timestamp"], unique=False
    )
    op.create_index(
        "ix_vehicle_positions_trip_id_feed_timestamp",
        "vehicle_positions",
        ["trip_id", "feed_timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


# Drop the new vehicle_positions indexes and the stop_events table.
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_vehicle_positions_trip_id_feed_timestamp", table_name="vehicle_positions")
    op.drop_index("ix_vehicle_positions_feed_timestamp", table_name="vehicle_positions")
    op.drop_index("ix_stop_events_route_direction_stop_arrival", table_name="stop_events")
    op.drop_index("ix_stop_events_observed_arrival", table_name="stop_events")
    op.drop_table("stop_events")
    # ### end Alembic commands ###
