"""route hourly performance

Revision ID: 35f2493b6264
Revises: ea6b3d7aeb1d
Create Date: 2026-09-14 13:14:39.236108

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "35f2493b6264"
down_revision: str | None = "ea6b3d7aeb1d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Create route_hourly_performance: one row of reliability figures per route, direction, and UTC
# hour, rebuilt by the aggregate_hourly job, with an index on hour_bucket for period queries.
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "route_hourly_performance",
        sa.Column("route_id", sa.Text(), nullable=False),
        sa.Column("direction_id", sa.SmallInteger(), nullable=False),
        sa.Column("hour_bucket", sa.DateTime(timezone=True), nullable=False),
        sa.Column("day_of_week", sa.SmallInteger(), nullable=False),
        sa.Column("hour_of_day", sa.SmallInteger(), nullable=False),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column("avg_delay_seconds", sa.Float(), nullable=True),
        sa.Column("avg_abs_delay_seconds", sa.Float(), nullable=True),
        sa.Column("p90_delay_seconds", sa.Float(), nullable=True),
        sa.Column("on_time_percentage", sa.Float(), nullable=True),
        sa.Column("headway_sample_count", sa.Integer(), nullable=False),
        sa.Column("avg_headway_seconds", sa.Float(), nullable=True),
        sa.Column("avg_scheduled_headway_seconds", sa.Float(), nullable=True),
        sa.Column("headway_cv", sa.Float(), nullable=True),
        sa.Column("excess_wait_seconds", sa.Float(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "route_id", "direction_id", "hour_bucket", name=op.f("pk_route_hourly_performance")
        ),
    )
    op.create_index(
        "ix_route_hourly_performance_hour_bucket",
        "route_hourly_performance",
        ["hour_bucket"],
        unique=False,
    )
    # ### end Alembic commands ###


# Drop route_hourly_performance and its index.
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_route_hourly_performance_hour_bucket", table_name="route_hourly_performance")
    op.drop_table("route_hourly_performance")
    # ### end Alembic commands ###
