"""realtime vehicle tables

Revision ID: 651b8ba045fa
Revises: 99a4398e6108
Create Date: 2026-09-13 01:11:08.121446

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "651b8ba045fa"
down_revision: str | None = "99a4398e6108"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Create the realtime tables: realtime_feed_state (last snapshot per feed), vehicle_latest (newest
# state per vehicle), and vehicle_positions (history, partitioned by day; the poller creates the
# daily partitions at runtime).
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "realtime_feed_state",
        sa.Column("feed", sa.Text(), nullable=False),
        sa.Column("header_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("entity_count", sa.Integer(), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("feed", name=op.f("pk_realtime_feed_state")),
    )
    op.create_table(
        "vehicle_latest",
        sa.Column("vehicle_id", sa.Text(), nullable=False),
        sa.Column("route_id", sa.Text(), nullable=True),
        sa.Column("feed_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("trip_id", sa.Text(), nullable=True),
        sa.Column("direction_id", sa.SmallInteger(), nullable=True),
        sa.Column("service_date", sa.Date(), nullable=True),
        sa.Column("stop_id", sa.Text(), nullable=True),
        sa.Column("stop_sequence", sa.Integer(), nullable=True),
        sa.Column("current_status", sa.Text(), nullable=True),
        sa.Column("schedule_relationship", sa.Text(), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lon", sa.Float(), nullable=True),
        sa.Column("bearing", sa.Float(), nullable=True),
        sa.Column("delay_seconds", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("vehicle_id", name=op.f("pk_vehicle_latest")),
    )
    op.create_index(
        op.f("ix_vehicle_latest_route_id"), "vehicle_latest", ["route_id"], unique=False
    )
    op.create_table(
        "vehicle_positions",
        sa.Column("vehicle_id", sa.Text(), nullable=False),
        sa.Column("feed_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("trip_id", sa.Text(), nullable=True),
        sa.Column("route_id", sa.Text(), nullable=True),
        sa.Column("direction_id", sa.SmallInteger(), nullable=True),
        sa.Column("service_date", sa.Date(), nullable=True),
        sa.Column("stop_id", sa.Text(), nullable=True),
        sa.Column("stop_sequence", sa.Integer(), nullable=True),
        sa.Column("current_status", sa.Text(), nullable=True),
        sa.Column("schedule_relationship", sa.Text(), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lon", sa.Float(), nullable=True),
        sa.Column("bearing", sa.Float(), nullable=True),
        sa.Column("delay_seconds", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("vehicle_id", "feed_timestamp", name=op.f("pk_vehicle_positions")),
        postgresql_partition_by="RANGE (feed_timestamp)",
    )
    op.create_index(
        "ix_vehicle_positions_route_id_feed_timestamp",
        "vehicle_positions",
        ["route_id", "feed_timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


# Drop the realtime tables. Dropping vehicle_positions also drops all of its daily partitions.
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_vehicle_positions_route_id_feed_timestamp", table_name="vehicle_positions")
    op.drop_table("vehicle_positions")
    op.drop_index(op.f("ix_vehicle_latest_route_id"), table_name="vehicle_latest")
    op.drop_table("vehicle_latest")
    op.drop_table("realtime_feed_state")
    # ### end Alembic commands ###
